# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.9.1
    working_directory: /go/src/github.com/atom-deps/zlog
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go get github.com/schrej/godacov
      - run: go get -v -t -d ./...
      - run: go test -v -coverprofile=coverage.out ./...
      - run: godacov -t ${CODACY_TOKEN} -r ./coverage.out -c ${CIRCLE_SHA1}